inherit:
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 50
    n_embd: 128
    n_layer: 12
    n_head: 8

training:
    task: mixed_function
    data: gaussian
    task_kwargs:
        function_types: ['linear', 'quadratic', 'neural_net', 'decision_tree']
        distribution: 'uniform'  # uniform distribution across function types
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500000
    curriculum:
        stages:
            - functions: ['linear']
              threshold: 0.1
              steps: 100000
            - functions: ['linear', 'quadratic']
              threshold: 0.15
              steps: 100000
            - functions: ['linear', 'quadratic', 'neural_net']
              threshold: 0.2
              steps: 150000
            - functions: ['linear', 'quadratic', 'neural_net', 'decision_tree']
              threshold: 0.25
              steps: 150000
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 50
            end: 50
            inc: 2
            interval: 2000

evaluation:
    metrics:
        - mse_per_class
        - adaptation_speed
        - class_confusion
    visualization:
        - learning_curves
        - class_distribution
        - hidden_state_analysis

out_dir: ../models/mixed_function

wandb:
    name: "mixed_function_base"
    tags: ["mixed", "curriculum"]